apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: frontend
  labels:
    name: loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: dogs
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  template:
    metadata:
      labels:
        app: dogs
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: datianshi/cats-dogs-frontend
        env:
        - name: PORT
          value: "8080"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: backend
        image: datianshi/cats-dogs-backend
        env:
        - name: PORT
          value: "8080"
